# Generated by Django 5.2.15 on 2026-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='Müziğin Kalbinde Üretim', max_length=200, verbose_name='Hakkımızda başlığı')),
                ('about_text', models.TextField(default='Kam Müzik olarak, uluslararası standartlarda ses kayıt, albüm ve klip yapımı hizmetleri sunuyoruz. Sanatçılarımızın eserlerini dijital platformlarda dinleyicilerle buluşturuyoruz.', verbose_name='Hakkımızda metni')),
                ('studio_title', models.CharField(default='Stüdyomuz', max_length=200, verbose_name='Stüdyo başlığı')),
                ('studio_text', models.TextField(blank=True, default='Son teknoloji ekipmanlarla donatılmış profesyonel kayıt stüdyomuz.', verbose_name='Stüdyo açıklaması')),
                ('contact_email', models.EmailField(default='info@kammuzik.com', max_length=254, verbose_name='İletişim e-postası')),
                ('contact_phone', models.CharField(default='+90 555 123 45 67', max_length=40, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Site İçeriği',
                'verbose_name_plural': 'Site İçeriği',
            },
        ),
        migrations.CreateModel(
            name='StudioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='studio/', verbose_name='Fotoğraf')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Görünür mü?')),
            ],
            options={
                'verbose_name': 'Stüdyo Fotoğrafı',
                'verbose_name_plural': 'Stüdyo Fotoğrafları',
                'ordering': ['order', 'id'],
            },
        ),
    ]
