# Generated by Django 5.2.15 on 2026-07-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='whatsapp_number',
            field=models.CharField(default='905551234567', help_text='Örnek: 905551234567 (başında 90, + veya boşluk YOK)', max_length=20, verbose_name='WhatsApp numarası (uluslararası, + ve boşluksuz)'),
        ),
    ]
