# Generated by Django 5.2.15 on 2026-07-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitecontent_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='whatsapp_number',
        ),
    ]
