# Generated by Django 5.2.15 on 2026-07-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_sitecontent_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Haritalar → Paylaş → Harita yerleştir → iframe içindeki src="..." linkini yapıştır.', max_length=1000, verbose_name='Google Harita linki (embed src)'),
        ),
    ]
