# Generated by Django 5.2.15 on 2026-07-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sitecontent_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Anasayfa üst bölümünün arka planı. Yatay, koyu tonlu bir stüdyo fotoğrafı ideal.', null=True, upload_to='hero/', verbose_name='Hero arka plan görseli'),
        ),
    ]
