# Generated by Django 5.2.15 on 2026-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sitecontent_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='show_recent_actions',
            field=models.BooleanField(default=True, help_text='Kapatılırsa yönetim panosunda son işlemler listesi gizlenir.', verbose_name="Panelde 'Son Eylemler'i göster"),
        ),
    ]
