# Generated by Django 5.2.15 on 2026-07-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sitecontent_show_recent_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='hero_subtitle',
            field=models.CharField(default='Albüm & single yapımı, klip çekimi ve dijital platform yayıncılığı.', max_length=300, verbose_name='Hero alt açıklaması'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_title',
            field=models.CharField(default='Dünya Standartlarında', max_length=200, verbose_name='Hero başlığı (1. satır)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_title_accent',
            field=models.CharField(default='Ses ve Yapım', max_length=200, verbose_name='Hero başlığı (2. satır - vurgulu)'),
        ),
    ]
