# Generated by Django 5.2.15 on 2026-07-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_sitecontent_hero_subtitle_sitecontent_hero_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='logo',
            field=models.ImageField(blank=True, help_text='Sitenin ve panelin her yerinde kullanılacak logo. Kare veya yatay, şeffaf arka planlı (PNG) ideal.', null=True, upload_to='logo/', verbose_name='Logo'),
        ),
    ]
