# Generated by Django 5.2.15 on 2026-07-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_sitecontent_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='theme',
            field=models.CharField(choices=[('mavi', 'Mavi (Varsayılan)'), ('yesil', 'Yeşil'), ('mor', 'Mor'), ('turuncu', 'Turuncu')], default='mavi', help_text='Sitenin genel renk temasını belirler.', max_length=20, verbose_name='Site Teması'),
        ),
    ]
