# Generated by Django 5.2.15 on 2026-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_sitecontent_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='theme',
            field=models.CharField(choices=[('mavi', 'Mavi (Varsayılan)'), ('karbon', 'Koyu Karbon (Turkuaz-Mor)'), ('gece', 'Gece Mavisi (Kehribar-Turuncu)')], default='mavi', help_text='Sitenin genel renk temasını belirler.', max_length=20, verbose_name='Site Teması'),
        ),
    ]
