"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+fy3_tz(+vkcw53kid_h95bas(b#)^_=4og4a=$!zg#p3kw^h&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.sitemaps",

    #Kendi app'lerimiz
    'catalog',
    "pages",
    "contact",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "pages.context_processors.site_content",
                "pages.context_processors.admin_stats",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "tr"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


STATICFILES_DIRS = []

# E-posta ayarları (Gmail SMTP)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

JAZZMIN_SETTINGS = {
    # Başlıklar
    "site_title": "Kam Müzik Yönetim",
    "site_header": "Kam Müzik",
    "site_brand": "Kam Müzik",
    "welcome_sign": "Kam Müzik Yönetim Paneline Hoş Geldiniz",
    "copyright": "Kam Müzik",

    # Üst menüyü sadeleştir (arkadaşın için gereksiz linkleri kaldır)
    "topmenu_links": [
        {"name": "Siteyi Görüntüle", "url": "/", "new_window": True},
    ],

    # Kullanıcıya gösterilmeyecek (kafa karıştıran) uygulamalar/modeller
    "hide_apps": [],
    "hide_models": ["auth.Group", "auth.User"],

    # Sol menü sırası — mantıklı bir akış
    "order_with_respect_to": [
        "catalog",
        "catalog.Song",
        "catalog.VideoClip",
        "catalog.Category",
        "catalog.Tag",
        "pages",
        "contact",
        "auth",
    ],

    # Her modele anlamlı ikon (Font Awesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "catalog.Song": "fas fa-music",
        "catalog.VideoClip": "fas fa-video",
        "catalog.Category": "fas fa-folder",
        "catalog.Tag": "fas fa-tag",
        "pages.SiteContent": "fas fa-sliders-h",
        "pages.StudioPhoto": "fas fa-images",
        "contact.ContactMessage": "fas fa-envelope",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # Görünüm
    "related_modal_active": True,   # ilişkili kayıtları pencerede aç (sayfa değiştirmeden)
    "custom_css": "catalog/css/admin_custom.css",
    "show_ui_builder": False,
    "recent_actions_limit": 50,
    "changeform_format": "horizontal_tabs",
    "show_sidebar": True,
    "navigation_expanded": True,

    "login_logo": None,
    "site_logo_classes": "img-circle",

    "usermenu_links": [
        {"name": "Parolamı Değiştir", "url": "admin:password_change", "icon": "fas fa-key"},
    ],
    
    "actions_sticky_top": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "default",
    "dark_mode_theme": None,
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar_fixed": True,
    "sidebar_fixed": True,
}

# Giriş/parola işlemleri sonrası yönlendirme
LOGIN_REDIRECT_URL = "/admin/"
LOGIN_URL = "/admin/login/"