# Generated by Django 5.2.15 on 2026-07-05 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-release_date', '-created_at'], 'verbose_name': 'Şarkı', 'verbose_name_plural': 'Şarkılar'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Etiket', 'verbose_name_plural': 'Etiketler'},
        ),
        migrations.AlterModelOptions(
            name='videoclip',
            options={'ordering': ['-release_date', '-created_at'], 'verbose_name': 'Video Klip', 'verbose_name_plural': 'Video Klipler'},
        ),
        migrations.AlterField(
            model_name='song',
            name='apple_music_url',
            field=models.URLField(blank=True, verbose_name='Apple Music linki'),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='catalog.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Kapak görseli'),
        ),
        migrations.AlterField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Süre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Yayında mı?'),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yayın tarihi'),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Kısa ad (URL)'),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_url',
            field=models.URLField(blank=True, verbose_name='Spotify linki'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='catalog.tag', verbose_name='Etiketler'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='song',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube linki'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='catalog.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Kapak görseli'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='director',
            field=models.CharField(blank=True, max_length=200, verbose_name='Yönetmen'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Yayında mı?'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yayın tarihi'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Kısa ad (URL)'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='catalog.tag', verbose_name='Etiketler'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube linki'),
        ),
    ]
