# Generated by Django 5.2.15 on 2026-07-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sanatçı Adı')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Kısa ad (URL)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name='Fotoğraf')),
                ('bio', models.TextField(blank=True, verbose_name='Biyografi / Açıklama')),
                ('role', models.CharField(blank=True, help_text='Örn: Rap Sanatçısı, Prodüktör, Söz Yazarı', max_length=120, verbose_name='Rol / Tür')),
                ('spotify_url', models.URLField(blank=True, verbose_name='Spotify')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('apple_music_url', models.URLField(blank=True, verbose_name='Apple Music')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Küçük numara önce görünür.', verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sanatçı',
                'verbose_name_plural': 'Sanatçılar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='catalog.artist', verbose_name='Sanatçı'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videoclips', to='catalog.artist', verbose_name='Sanatçı'),
        ),
    ]
